[tool.jsonschema_testing]
schema_file_exclude_filenames = []

definition_directory = "definitions"
schema_directory = "schemas"

instance_file_exclude_filenames = ['.yamllint.yml', '.travis.yml']
# instance_search_directories = ["hostvars/"]

[tool.jsonschema_testing.schema_mapping]
# Map instance filename to schema id which should be used to check the instance data contained in the file
'dns.yml' = ['schemas/dns_servers']
'syslog.yml' = ["schemas/syslog_servers"]