---
# Add additional stages in the order of execution here, and then under the job:include: key
stages:
  - "lint"
  - "test"

if: "type IN (pull_request)"  # Add in "branch" as an option if desired for branch testing as well

language: "python"
python:
  - 3.7
  - 3.8
  - 3.9

services:
  - "docker"

# Env, before_script, and script for test stage
env:
  matrix:
    - "ANSIBLE_VERSION=2.8.18"
    - "ANSIBLE_VERSION=2.9.17"
    - "ANSIBLE_VERSION=2.10.5"
before_script:
  - "pip install invoke toml"
  - "invoke build-image --nocache"
script:
  - "invoke pytest"

jobs:
  include:
    - stage: "lint"
      before_script:
        - "pip install invoke toml"
        - "invoke build-image --nocache"
      script:
        - "invoke black"
        - "invoke bandit"  # Bandit fails to function on > Py3.8 https://github.com/PyCQA/bandit/issues/639
        - "invoke pydocstyle"
        - "invoke flake8"
        - "invoke yamllint"
        - "invoke pylint"
