[tool.poetry]
name = "jsonschema_testing"
version = "0.1.0"
description = ""
authors = ["Phillip Simonds <phillip.simonds@networktocode.com>"]

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.1.2"
termcolor = "^1.1.0"
jsonschema = "^3.2.0"
toml = "^0.10.0"
ipdb = "^0.13.2"
"ruamel.yaml" = "^0.16.10"
jinja2 = "^2.11.2"
ansible = "^2.9.7"
jsonref = "^0.2"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
tox = "^3.15.0"
flake8 = "^3.7.9"
black = "^19.10b0"
yamllint = "^1.23.0"

[tool.poetry.scripts]
test-schema = "jsonschema_testing.test_schema:main"

[tool.black]
line-length = 120
target-version = ['py36']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | venv
  )/
  | urls.py
  | settings.py
)
'''

[tool.jsonschema_testing]
schema_file_extension = ".json"
schema_exclude_filenames = []
instance_file_extension = ".yml"
schema_search_directory = "./examples/schema/json/full_schemas/"
instance_exclude_filenames = ['.yamllint.yml', '.travis.yml']
schema_file_type = "json"
instance_search_directory = "./examples/hostvars/"
instance_file_type = "yaml"
[tool.jsonschema_testing.schema_mapping]
"dns.yml" = ['schemas/dns_servers']
'ntp.yml' = ["schemas/ntp"]
'syslog.yml' = ["schemas/syslog_servers"]
