[tool.jsonschema_testing]
schema_file_exclude_filenames = []

definition_directory = "definitions"
schema_directory = "schemas"

instance_file_exclude_filenames = ['.yamllint.yml', '.travis.yml']
# instance_search_directories = ["hostvars/"]

[tool.jsonschema_testing.schema_mapping]
# Map instance filename to schema filename
#'dns.yml' = ['schemas/dns_servers', 'http://networktocode.com/schemas/core/dns']
'dns.yml' = ['schemas/dns_servers']
# testing tag.. 'ntp.yml' = ["schemas/ntp", "missing"]
'syslog.yml' = ["schemas/syslog_servers"]